imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-seo
  - path: github.com/theNewDynamic/hugo-module-tnd-snipcart
  - path: github.com/theNewDynamic/hugo-module-tnd-func
  - path: github.com/theNewDynamic/hugo-module-tnd-socials