visitorGuideLink: /visitor-guide
tnd_seo:
  # Used for articles without images
  default_image: "/img/shore_acres_medium.jpg"
  # if true will use the SEO data object to output an json+ld script tag.
  jsonld: true
  disable_title_tag: false
  # if true module will handle follow/nofollow tags for pages depending on environment and Front Matter setting.
  enable_follow: true
tnd_snipcart:
  front_matter_key: product
  api_key: YzIyNDVmNWItNDA4NS00ZGRkLThmNTctNDFlZDNiMWM0ODM4NjM3Mzk1ODk4MTcxNDQ2NTI4
  global:
    modal-style: side
  forms:
    _default:
      buy_button_text: Add to Cart
      buy_button_classes: ""
      fields:
        - id: quantity
          name: Quantity
        - id: size
          name: Size
    single:
      buy_button_text: Add to Cart
      buy_button_classes: ""
      fields: