visitorGuideLink: /visitor-guide
tnd_seo:
  # Used for articles without images
  default_image: "/img/shore_acres_medium.jpg"
  # if true will use the SEO data object to output an json+ld script tag.
  jsonld: true
  disable_title_tag: false
  # if true module will handle follow/nofollow tags for pages depending on environment and Front Matter setting.
  enable_follow: true
tnd_snipcart:
  front_matter_key: product
  api_key: YzIyNDVmNWItNDA4NS00ZGRkLThmNTctNDFlZDNiMWM0ODM4NjM3Mzk1ODk4MTcxNDQ2NTI4
  global:
    modal-style: side
  forms:
    _default:
      buy_button_text: Add to Cart
      buy_button_classes: ""
      fields:
        - id: quantity
          name: Quantity
        - id: size
          name: Size
    single:
      buy_button_text: Add to Cart
      buy_button_classes: ""
      fields:
tnd_socials:
  services:
  - name: facebook
    handle: OregonsAdventureCoast
  - name: twitter
    handle: travelcoosbay
  - name: instagram
    handle: travelcoosbay
  - name: pinterest
    handle: travelcoosbay
  - name: youtube
    handle: CoosBayOregon
  - name: tiktok
    handle: oregonsadventurecoast
    url: https://www.tiktok.com/@oregonsadventurecoast?lang=en
tnd_search:
  template_storage: 
    templates_menu_item: &templates_menu_item
      | 
      <label class="{{cssClasses.label }} {{#disabled}}disabled{{/disabled}}">
        <input type="checkbox" class="ais-refinement-list–checkbox" value="{{label}}" {{#isRefined}}checked="true"{{/isRefined}} {{#disabled}}disabled{{/disabled}}>
        {{label}}
      </label>

  service: meili
  instantsearch:
  - name: lodging
    indexName: lodging
    appId: https://ms-f3fd9122c128-118.saas-nyc.meili.dev
    apiKey: ec82d24790da484ef22f185eac5f04c22016f58bf4857afcec6c88d8363e72d2
    hitsPerPage: 1000
    widgets:
    - name: stats
      templates:
        text: |
          {{#hasNoResults}}0 results{{/hasNoResults}}
          {{#hasOneResult}}1 result{{/hasOneResult}}
          {{#hasManyResults}}{{#helpers.formatNumber}}{{nbHits}}{{/helpers.formatNumber}} results{{/hasManyResults}}
    - name: clearRefinements
      container: '#clear'
      classes:
        button: landing-button
      templates:
        resetLabel: |-
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.0.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M0 256C0 114.6 114.6 0 256 0C397.4 0 512 114.6 512 256C512 397.4 397.4 512 256 512C114.6 512 0 397.4 0 256zM175 208.1L222.1 255.1L175 303C165.7 312.4 165.7 327.6 175 336.1C184.4 346.3 199.6 346.3 208.1 336.1L255.1 289.9L303 336.1C312.4 346.3 327.6 346.3 336.1 336.1C346.3 327.6 346.3 312.4 336.1 303L289.9 255.1L336.1 208.1C346.3 199.6 346.3 184.4 336.1 175C327.6 165.7 312.4 165.7 303 175L255.1 222.1L208.1 175C199.6 165.7 184.4 165.7 175 175C165.7 184.4 165.7 199.6 175 208.1V208.1z"/></svg>
          Clear All Filters
      includeAttributes: ['category', 'city', 'amenities']
    - name: refinementList
      container: '#menu-city'
      attribute: city
      js: js_cities
      classes:
        list: reset-list
        count: hidden
        item: refinement-item
      templates:
        item: *templates_menu_item
    - name: refinementList
      container: '#menu-category'
      attribute: category
      js: js_categories
      sortBy:
      - 'name:asc'
      - 'count:asc'
      classes:
        list: reset-list
        count: hidden
        item: refinement-item
      templates:
        item: *templates_menu_item
    - name: refinementList
      container: '#menu-amenities'
      attribute: amenities
      operator: and
      limit: 15
      js: js_amenities
      templates:
        item: *templates_menu_item
      classes:
        list: reset-list
        count: hidden
        item: refinement-item
     # templates:
     #   item: *templates_menu_item
    #- name: pagination
    #  scrollTo: false
    #  classes:
    #    root: grid-pagination
    - name: hits
      js: hits
      classes:
        root: 'lodging-list'
        list: 'm-grid'
        item: 'm-lodging-item'
      templates:
        item: |
          <div class="photo" style="background-image:url({{image}});" alt="{{title}}">
          </div>

          <div class="content marker-content">
            <div class="category">
              {{category}}
            </div>
            <div class="location">
              <h2>{{title}}</h2>
              <p class="address">
                {{street}}<br>
                {{city}}, {{state}} {{zip}}<br>
                {{#phone_links}}
                {{{.}}}
                {{/phone_links}}
              </p>
            </div>
            <div class="description">
                <strong>
                Units: {{units}} • {{cost}}: 
                </strong>
                {{description}}
            </div>
            <div class="m-lodging-item__footer">
              <div class="amenities">
                <div class="amenity-list clearfix">
                  <ul>
                  {{#amenities}}
                    <li class="icon-lodging {{.}}" title="{{.}}"></li>
                  {{/amenities}}
                  </ul>
                </div>
              </div>
              <div class="links clearfix">
                {{#map_link}}
                <span class="map"><a href="{{map_link}}" target="_blank"><span class="icon"><i class="fas fa-map-marker-alt" aria-hidden="true"></i></span> Map</a></span>
                {{/map_link}}
                {{#website}}
                <span class="website "><a href="{{website}}" target="_blank"><span class="icon"><i class="fas fa-globe" aria-hidden="true"></i></span> Website</a></span>
                {{/website}}
              </div>
            </div>
          </div>
    - name: geoSearch
      js: map
      classes:
        redo: hidden
      container: '#map'