---
new_page_extension: md
auto_deploy: false
admin_path: "/static/content/"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: Home
  templates:
  - home
- type: directory
  path: content
  label: Main Pages
  create: all
  match: "*.md"
  exclude: _index.md
  templates:
  - regular-pages
- type: directory
  path: content/sitepages
  label: Other Pages
  create: all
  match: "**/*"
  templates:
  - regular-pages
- type: directory
  path: content/adventure
  label: Adventures
  create: all
  match: "**/*"
  templates:
  - adventure
- type: directory
  path: content/blog
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/event
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: content/tripideas
  label: Trip Ideas
  create: all
  match: "**/*"
  templates:
  - trip-ideas
- type: directory
  path: content/lodgingitems
  label: Lodgings
  create: all
  match: "**/*"
  templates:
  - lodging
- type: directory
  path: content/tourandequipment
  label: Tours and Equipment
  create: all
  match: "**/*"
  templates:
  - tours-and-equipment
- type: heading
  label: Other
- type: document
  path: data/redirects.yaml
  label: Redirects
- type: document
  path: site/data/taxonomies.yaml
  label: Taxonomies
- type: heading
  label: Information
- type: document
  path: docs/status.md
  label: Status
  match: "**/*"
  read_only: true
upload_dir: static/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.52'
