---
label: Product
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: hover_image
  type: file
  config:
    maxSize: 64
  label: Hover Image
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
  description: 'Description of the product to be displayed on the web site '
- name: product
  type: field_group
  config: {}
  fields:
  - name: id
    type: text
    config:
      required: false
    label: ID
    description: Will be used as product ID in the store back office.
  - name: price
    type: number
    label: Price
    description: ''
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  - name: weight
    type: number
    label: Weight
    description: The weight of the product in ounces
    default: 0
    required: true
    config:
      min: 
      max: 
      step: 
  - name: description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  - name: custom_fields
    type: blocks
    label: Custom Fields
    template_types:
    - product-field-size
    config:
      min: 
      max: 
  label: Product
pages:
- content/products/2020-custom-myrtlewood-christmas-ornament.md
- content/products/black-crab-t-shirt.md
- content/products/branded-crab-measure-tool.md
- content/products/custom-crab-face-mask.md
- content/products/grey-embroidered-baseball-cap.md
- content/products/grey-heather-crab-hoodie.md
- content/products/jewelry-charm-bracelet.md
- content/products/jewelry-crab-charm.md
- content/products/jewelry-wave-hidden-charm.md
- content/products/magnet-charleston.md
- content/products/magnet-coos-bay-oregon.md
- content/products/magnet-north-bend-oregon.md
- content/products/magnet-oregon-s-adventure-coast-crab.md
- content/products/myrtlewood-pen-mini.md
- content/products/myrtlewood-pen-slimline.md
- content/products/myrtlewood-pen.md
- content/products/red-crab-t-shirt-1.md
- content/products/sticker-dark.md
- content/products/sticker-reel-adventures.md
- content/products/sticker-whiskey-run-mtn-biking.md
- content/products/stickers-storm-watching.md
